### ISSUE TITLE
hc22000 file only written on exit

### ISSUE THREAD

**Issue by kawaiipantsu** [Ragnt/AngryOxide#17]
Hi,

Going over your code seems to confirm that the Hashcat .hc22000 file is only written once you quit the application and quit it cleanly.
For us that perhaps are going for multiple targets (ie. all) it would be much better that that the hc22000 file is written continuous doing the application running.

I've now had multiple times where it ran for let's say 2-3 days, unable to quit it cleanly as the "q" function did not work/respond and therefore i never get the hc22000 file.

It would be nice that it took the --output naming and then created a file just like the kismetdb and pcapng files but where it dumped (appended) the hc22000 strings everytime it was done collecting a full 4 way handshake for any device.

Hope that makes sense

**Comment by Ragnt** [comment]
Yep, makes perfect sense.

I have this on the roadmap for version 0.9.0, but I will raise its priority and work on getting this done this weekend.

I am still working on figuring out exactly why a notably long capture is causing a UI lock, if you are doing this frequently and could provide some details such as memory and CPU usage comparisons on your system that would be appreciated. Is AO still getting/processing frames when the this happens?

**Comment by Ragnt** [comment]
To be clear:

> It would be nice that it took the --output naming and then created a file just like the kismetdb and pcapng files but where it dumped (appended) the hc22000 strings everytime it was done collecting a full 4 way handshake for any device.

Are you asking for a single file, named using the same --output naming scheme, that contains every valid hashline collected, regardless of the AP it belongs to?

**Comment by Ragnt** [comment]
Closing this issue as the branch has been merged.
