### ISSUE TITLE
0.8.5 no frames on Kali linux

### ISSUE THREAD

**Issue by meditant** [Ragnt/AngryOxide#21]
Hello,

The previous version work well for me but the latest not get frames and find no network. STay blocked in frequency 5180 (36) just Ers continue to advance.
No error message.

I try 2 network adapter on intel and a Alfa.

The programme work a can (q) for quit.

I am in france if frequency region can influence.

Best regards

**Comment by Ragnt** [comment]
What is the command you are using and what is the output when the tool first starts, before the UI shows.

AO will always be limited based on frequency region, but only that it will only be able to use enabled frequencies as reported by netlink.

**Comment by meditant** [comment]
Starting AngryOxide... 😈
💲 Interface Summary:
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Interface: wlan0                                                                                         ┃
┃ Index: 3 | Driver: iwlwifi                                                                               ┃
┃ Mode: IftypeStation | Active Monitor: false                                                              ┃
┃ Modes: Adhoc, Station, Ap, ApVlan, Monitor, P2P Client, P2P Go, P2P Device                               ┃
┃ State: Up                                                                                                ┃
┃ Current Frequency: 5180 (36)                                                                             ┃
┃ Enabled Bands/Channels:                                                                                  ┃
┃                                                                                                          ┃
┃ Band2GHz:                                                                                                ┃
┃   [2412 (1)]       [2417 (2)]       [2422 (3)]       [2427 (4)]       [2432 (5)]       [2437 (6)]        ┃
┃   [2442 (7)]       [2447 (8)]       [2452 (9)]       [2457 (10)]      [2462 (11)]      [2467 (12)]       ┃
┃   [2472 (13)]                                                                                            ┃
┃                                                                                                          ┃
┃ Band5GHz:                                                                                                ┃
┃   [5180 (36)]      [5200 (40)]      [5220 (44)]      [5240 (48)]      [5260 (52)]      [5280 (56)]       ┃
┃   [5300 (60)]      [5320 (64)]      [5500 (100)]     [5520 (104)]     [5540 (108)]     [5560 (112)]      ┃
┃   [5580 (116)]     [5600 (120)]     [5620 (124)]     [5640 (128)]     [5660 (132)]     [5680 (136)]      ┃
┃   [5700 (140)]     [5745 (149)]     [5765 (153)]     [5785 (157)]     [5805 (161)]     [5825 (165)]      ┃
┃                                                                                                          ┃
┃                                                                                                          ┃
┃ Band6GHz:                                                                                                ┃
┃   [5955 (1.6e)]    [5975 (5.6e)]    [5995 (9.6e)]    [6015 (13.6e)]   [6035 (17.6e)]   [6055 (21.6e)]    ┃
┃   [6075 (25.6e)]   [6095 (29.6e)]   [6115 (33.6e)]   [6135 (37.6e)]   [6155 (41.6e)]   [6175 (45.6e)]    ┃
┃   [6195 (49.6e)]   [6215 (53.6e)]   [6235 (57.6e)]   [6255 (61.6e)]   [6275 (65.6e)]   [6295 (69.6e)]    ┃
┃   [6315 (73.6e)]   [6335 (77.6e)]   [6355 (81.6e)]   [6375 (85.6e)]   [6395 (89.6e)]   [6415 (93.6e)]    ┃
┃                                                                                                          ┃
┃                                                                                                          ┃
┃                                                                                                          ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
💲 No target list provided... everything is a target 😏
💲 No whitelist list provided.

======== Hop Channels ========
 └ Band 2 Channels:
   ├ 1
   ├ 6
   └ 11
==============================

💲 Attack Rate: Normal (2)
💲 Setting wlan0 down.
💲 Randomizing wlan0 mac to 481XXXXXXXX
💲 Setting wlan0 to Monitor mode. ("active" flag: false)
💲 Setting wlan0 up.
💲 OUI Records Imported: 50153
💲 Sockets Opened [Rx: 5 | Tx: 6]
🎩 KICKING UP THE 4D3D3D3 🎩

======================================================================

💲 Cleaning up...
💲 Setting wlan0 down.
💲 Restoring wlan0 MAC back to 04cXXXXXXXX.
💲 Setting wlan0 to station mode.
💲 Stopping Threads

AngryOxide did not collect any results. 😔 Try running longer, or check your interface?
📦 Creating Output Tarball (oxide-2024-02-18_10-05-28.tar.gz).
Please wait...

Complete! Happy Cracking! 🤙

**Comment by meditant** [comment]
Maybe a problem with dependent library because i compil 0.8.3 and same probleme i try with 0.8.1.

**Comment by meditant** [comment]
I try with 0.8.1 and same problem, angryoxide work same days ago on this machine. I make kali linux upgrade between.
I try wifite2 with this machine and network adapter and it's work i can see wifi ap and machines.
I try with kali on Pinephone and Pinephone Pro now.

**Comment by meditant** [comment]
I think I've found a solution; the problem comes from the adapter. I have many WiFi adapters, and I've prepared a list of those that work (OK) and those that do not work (KO) with AngryOxide.

**Comment by meditant** [comment]
I test with some usb wifi adapter with kali linux on X86 : 

OK : 
ALFA AWUS036ACH (rRTL8812au)
ALFA AWUS036ACS (RTL8812au)
ALFA AWUS036ACM (MT7612u)
COMFAST CF926AC v2 (MT7612u)
BrosTrend AC5 v2 (rtw_8821cu)

BUG : 
No-Name (MT7601u)
Crash after fews seconds : 
thread 'main' panicked at src/[main.rs:998](http://main.rs:998/):10
called 'Option::unwrap()' on a 'None' value

KO (No find network or find packets) : 
ALFA AWUS036AXML (MediaTek MT7921U)
TP-Link Archer T3U (RTW_8822bu)

**Comment by Ragnt** [comment]
Ah, okay. 

There is an identified and reported bug in the 7921 and 7601 drivers that causes active monitor mode to essentially break the driver. 

Angry Oxide will automatically put the card in active monitor mode if it reports that it is capable, because there are major baseband performance benefits.

You can disable active monitor in AO using the —noactive flag.


See here: 
https://github.com/openwrt/mt76/issues/839
https://github.com/morrownr/USB-WiFi/issues/107


As for the crash, that may be fixed in the latest dev build I plan on merging soon.

**Comment by Ragnt** [comment]
The Intel adapter shouldn’t be having that issue, but considering it’s iwlwifi and labeled wlan0, is there a chance that NetworkManager or another process is running and controlling this adapter? 

The adapter going back into Station mode because of network manager is a case where I have seen these exact circumstances (channel stuck, no frames)

**Comment by meditant** [comment]
Thanks your app is fantastic !

**Comment by Ragnt** [comment]
Thank you, let me know if the issues persist!

**Comment by meditant** [comment]
Nice ! I used airmon-nr check kill to kill all process and after angryoxide work well with Intel AX210 card !!!
You are the best !
