### ISSUE TITLE
Crash on Pinephone Pro with Kali Linux Nethunter Pro

### ISSUE THREAD

**Issue by meditant** [Ragnt/AngryOxide#22]
Hi,

I have this crash on Pinephone Pro with Kali Linux : 

Attack Rate: Normal (2)
Setting wlani down.
Randomizing wlani mac to 18xxxxxx
Setting wlani to Monitor mode. ("active" flag: true)
Setting wlan1 up.
OUI Records Imported: 50153
thread 'main' panicked at src/rawsocks.rs: 138:43:
called Result:: unwrap()' on an 'Err" value: Other("Missing patch version component")
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace

Latest kali linux nethunter pro and COMFAST CF926AC v2 (MT7612u), ALFA AWUS036ACS (RTL8812au), ALFA AWUS036ACM (MT7612u) i dont try other adapters.

**Comment by Ragnt** [comment]
What does /proc/sys/kernel/osrelease contain?

**Comment by meditant** [comment]
6.6-rockchip

**Comment by Ragnt** [comment]
Yeah, that would be why.

It’s not a valid Linux kernel version, so AO doesn’t know what to do. I’ll write a handler that defaults to the safest possible configuration if it doesn’t understand the version info and it’ll be in the latest dev branch until I merge it in 0.8.6.

**Comment by meditant** [comment]
Great

**Comment by Ragnt** [comment]
This should be good to go in 0.8.6+

Closing
