### ISSUE TITLE
Hello!

Could you Run pixie-dust attack and get a few PSK in the moment.
I would love to ser that

Thanks its a awesome tool.


### ISSUE THREAD

**Issue by chunga88** [Ragnt/AngryOxide#25]

**Comment by Ragnt** [comment]
I’ll look into the feasibility of this, but the plan was never to do any brute forcing in AO itself. 

I should be grabbing the necessary information to pass to pixie-wps however, and will look into making that happen.

**Comment by chunga88** [comment]
Thanks.
If you look to oneshot.py in GitHub maybe its the easy Path...
Thanks gain
Hope you look INTO it!

A sábado, 24/02/2024, 13:40, rage ***@***.***> escreveu:
