### ISSUE TITLE
thread 'main' panicked at src/main.rs:3002:37:

### ISSUE THREAD

**Issue by jakkpotts** [Ragnt/AngryOxide#30]
Shortly, after launching application, program crashes.

**To Reproduce**
This only started occurring after running tool with additional channels to hop, that being 1,3,4,6,7,11,40,48
Prior to issue, I had ran the tool on default settings for quite a while with success.

**Output**
`sudo angryoxide --whitelist whitelist.txt -c 1,3,4,6,7,11,40,48 -i wlan0
Starting AngryOxide... 😈
💲 Interface Summary:
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Interface: wlan0                                                          ┃
┃ Index: 6 | Driver: mt76x2u                                                ┃
┃ Mode: IftypeMonitor | Active Monitor: true                                ┃
┃ Modes: Adhoc, Station, Ap, ApVlan, Monitor, MeshPoint, P2P Client, P2P Go ┃
┃ State: Dormant                                                            ┃
┃ Current Frequency: 5200 (40)                                              ┃
┃ Enabled Bands/Channels:                                                   ┃
┃                                                                           ┃
┃ Band2GHz:                                                                 ┃
┃   [2412 (1)]       [2417 (2)]       [2422 (3)]       [2427 (4)]           ┃
┃   [2432 (5)]       [2437 (6)]       [2442 (7)]       [2447 (8)]           ┃
┃   [2452 (9)]       [2457 (10)]      [2462 (11)]      [2467 (12)]          ┃
┃   [2472 (13)]      [2484 (14)]                                            ┃
┃                                                                           ┃
┃ Band5GHz:                                                                 ┃
┃   [5180 (36)]      [5200 (40)]      [5220 (44)]      [5240 (48)]          ┃
┃   [5260 (52)]      [5280 (56)]      [5300 (60)]      [5320 (64)]          ┃
┃   [5500 (100)]     [5520 (104)]     [5540 (108)]     [5560 (112)]         ┃
┃   [5580 (116)]     [5600 (120)]     [5620 (124)]     [5640 (128)]         ┃
┃   [5660 (132)]     [5680 (136)]     [5700 (140)]     [5720 (144)]         ┃
┃   [5745 (149)]     [5765 (153)]     [5785 (157)]     [5805 (161)]         ┃
┃   [5825 (165)]                                                            ┃
┃                                                                           ┃
┃                                                                           ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
💲 No target list provided... everything is a target 😏

========= White List =========
 ├ SSID: CenturyLink1665
 └ SSID: CenturyLink1665_5G
========== Total: 2  ==========

======== Hop Channels ========
 ├ Band 5 Channels:
 │ ├ 40
 │ └ 48
 └ Band 2 Channels:
   ├ 1
   ├ 3
   ├ 4
   ├ 6
   ├ 7
   └ 11
==============================

💲 Dwell Time: 2
💲 Attack Rate: Normal (2)
💲 Setting wlan0 down.
💲 Randomizing wlan0 mac to 82516ed507c5
💲 Setting wlan0 to Monitor mode. ("active" flag: true)
💲 Setting wlan0 up.
💲 OUI Records Imported: 50153
💲 Sockets Opened [Rx: 5 | Tx: 6]

🎩 KICKING UP THE 4D3D3D3 🎩

======================================================================

thread 'main' panicked at src/main.rs:3002:37:
Could not open hashfile for writing. (zEQQ3XJPK+30/+aP.hc22000).
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`

**Backtrace output**
`stack backtrace:
   0:           0x7d4a14 - std::backtrace_rs::backtrace::libunwind::trace::h077be8d17a343ba0
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:           0x7d4a14 - std::backtrace_rs::backtrace::trace_unsynchronized::he9bae998f19d1192
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:           0x7d4a14 - std::sys_common::backtrace::_print_fmt::h3cb0a25ea4e06fd3
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:68:5
   3:           0x7d4a14 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4d40c874ac3055f9
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:44:22
   4:           0x817fcc - core::fmt::rt::Argument::fmt::h2aa676397f4d236d
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
   5:           0x817fcc - core::fmt::write::hbc8bab57647a8d59
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
   6:           0x7d17f0 - std::io::Write::write_fmt::h6830a27da260044c
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/mod.rs:1810:15
   7:           0x7d4840 - std::sys_common::backtrace::_print::h45e3ba4a460b54dc
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:47:5
   8:           0x7d4840 - std::sys_common::backtrace::print::ha90ccebd320c1f16
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:34:9
   9:           0x7d61dc - std::panicking::default_hook::{{closure}}::hea5e0840e75cbd54
  10:           0x7d5efc - std::panicking::default_hook::h2da0c6e28ccefbb5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:292:9
  11:           0x7d67b8 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hadc01b877337b2a0
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2029:9
  12:           0x7d67b8 - std::panicking::rust_panic_with_hook::he82b80ac427cd507
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:783:13
  13:           0x7d6530 - std::panicking::begin_panic_handler::{{closure}}::h9c22c275c948bda0
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
  14:           0x7d4ee4 - std::sys_common::backtrace::__rust_end_short_backtrace::hc10ef17bb01a2301
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
  15:           0x7d62d0 - rust_begin_unwind
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
  16:           0x4156c8 - core::panicking::panic_fmt::hefc208866c42565e
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
  17:           0x433174 - angryoxide::main::h19a9fbe428bacc64
  18:           0x4b5610 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc656463a074f5aff
  19:           0x4b5930 - std::rt::lang_start::{{closure}}::h675a739bd481ad16
  20:           0x7cb03c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h0d9bdbcc7f85e49e
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:284:13
  21:           0x7cb03c - std::panicking::try::do_call::h80136b13eeaadde3
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  22:           0x7cb03c - std::panicking::try::h2ec3fb47f55f59f5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  23:           0x7cb03c - std::panic::catch_unwind::h9af58d1941f17a40
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  24:           0x7cb03c - std::rt::lang_start_internal::{{closure}}::hb93b3739319681a0
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:48
  25:           0x7cb03c - std::panicking::try::do_call::hdaaeb7ab86a42ac4
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  26:           0x7cb03c - std::panicking::try::ha4a5aa32de9945d2
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  27:           0x7cb03c - std::panic::catch_unwind::h403dd3017366017d
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  28:           0x7cb03c - std::rt::lang_start_internal::h3242d8687092278a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:20
  29:           0x43cc24 - main
`

** Hardware (please complete the following information):**
 - apple m2 air running kali linux on vmware
 - kali
 - Panda PAU0D (MediaTek Inc. MT7612U chipset)

**Comment by GobiasSomeCoffeeCo** [comment]
Did it only happen this once? And was the name of the AP "zEQQ3XJPK+30/+aP", or is there an AP with that name in your environment? I noticed that's the file name it errored out on. Which given the fact it contains a '+' and a '/' could be problematic for writing in a Linux file structure.

**Comment by jakkpotts** [comment]
No, it stays consistent and crashes every time I have it hopping a particular combo of 2 and 5 ghz band channels. Nothing visible in the environment with that AP name that I can see, I noticed that as well. I suspect it is a hidden AP on the 5 ghz band or perhaps something is happening in the buffer. I will do some more testing report back. Excellent utility btw On Mar 15, 2024, at 4:56 PM, Gobias ***@***.***> wrote:﻿
Did it only happen this once? And was the name of the AP "zEQQ3XJPK+30/+aP", or is there an AP with that name in your environment? I noticed that's the file name it errored out on. Which given the fact it contains a '+' and a '/' could be problematic for writing in a Linux file structure.

**Comment by Ragnt** [comment]
Yeah, this is for sure because the AP has that SSID. I can add a check for illegal characters before attempting to write. 

For now, as a workaround you can use --combine to not write separate files per-AP.

**Comment by Ragnt** [comment]
This should be fixed after the latest commit. You will have to build from source until the next release.

**Comment by GobiasSomeCoffeeCo** [comment]
A fix was just pushed to the master branch that should fix your issue. If you want, you can do git pull and then cargo b --release and let us know how it goes.

**Comment by jakkpotts** [comment]
> This should be fixed after the latest commit. You will have to build from source until the next release.

yes, this solved the issue. thanks.
