### ISSUE TITLE
thread 'main' panicked

### ISSUE THREAD

**Issue by jakkpotts** [Ragnt/AngryOxide#32]
thread 'main' panicked at src/main.rs:1118:9:
Channel is None. Current Frequency: Frequency { frequency: None, width: Some(ChanWidth20Noht), channel: None, pwr: Some(2000) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
                                                                              

**To Reproduce**
sudo angryoxide --whitelist ~/working/config/whitelist.txt --interface wlan0 -b 2,5

** Hardware (please complete the following information):**
 - vmware fusion kali
 - OS: Mac OS Big Sur m2 air
 - Interface: Panda PAU0D

**Additional context**
about 10 seconds into launching the application, main thread panics and app terminates with the above output

**Comment by Ragnt** [comment]
This is the same error as:

https://github.com/Ragnt/AngryOxide/issues/27#issuecomment-1995191340

But seeing this with a PAU0D is alarming, as that means this isn't a driver issue.

What version of Kali is this? What kernel version?

**Comment by jakkpotts** [comment]
> This is the same error as:
> 
> [#27 (comment)](https://github.com/Ragnt/AngryOxide/issues/27#issuecomment-1995191340)
> 
> But seeing this with a PAU0D is alarming, as that means this isn't a driver issue.
> 
> What version of Kali is this? What kernel version?

6.6.9-arm64 // Kali 6.6.9-1kali1 (2024-01-08) // aarch64 GNU/Linux

**Comment by Ragnt** [comment]
Ah- the network down error is usually caused by another process trying to take over the interface. 

Try to kill wpa_supplicant and network manager, see what happens.

Since you are on Kali, try just running `sudo airmon-ng check kill` and run again, see if it happens.

**Comment by jakkpotts** [comment]
Yes indeed, that as well.  I opted to change the interface's name and add an entry to the NetworkManager service config file to ignore any interfaces with the specified name.
