### ISSUE TITLE
ERROR: GET_INTERFACE_STATUS 2

### ISSUE THREAD

**Issue by jakkpotts** [Ragnt/AngryOxide#34]
**Describe the bug**
Hard to say, I was running angryoxide on a raspi02w in the field, power bank as a power supply with a Panda AWUS036ACS adapter.  I've noticed that when I power on the raspi in my lab, where the default wifi network is located and configured with raspi-config (on the internal wifi interface, wlan0) then configure angryoxide to run on the adapter (panda0) and leave the lab -- I've noticed errors when I return to the lab, back into the environment where the NetworkManager service manages the wlan0 (Broadcom) wifi interface. I suspect this is causing an issue.

**Screenshots**
I was able to pull this:

`2024-04-20 22:57:29 UTC |   Info   | Sending Deauth: 86763f91c5a8 => ffffffffffff
💲 Cleaning up...

                                                                    ..%%%%%
                                                          ...    .%%%%%%""
                                                       .%%%%%%%/%%%%%"
                                     .....           .%%%%%%%%%%%%%%\
                                ..:::::::::::..      :;""  {_}\%%/%%%%%%..
                              .:::::::::::::::::.            {_}/{_}%%%%%%%
                             :::::::::::::::::::::            \\//    """\::
                            :::::::::::::::::::::::           \\//
---____-----__---------_____----....-----..--.....~-----_____-\\//---_____-
-----___---___----____--__--_.----...----...----..---__--_-___\\//--___--__
--____----__-___-----____----_...-----..--..---..___-------__\\//_-----____
___----____------____---__--___..--..-..----....___-----___--\\//_---__----
---___--___--__---__----___---___..----------._---____-----__\\//___---__--
--___---_-___-------______------___--___----___--__------___-\\//__--__----
____------____----_________------__                         \\//
--_____--__--____                              '            \\//  _
__---                 @            ,                  "          {_}
             .                            '

========== Error: (GET_INTERFACE_STATUS 2) Error response received from netlink: No such device (os error 19) ==========
💲 Setting alfa0 down.
💲 Restoring alfa0 MAC back to 00c0cab5b7a8.
💲 Setting alfa0 to station mode.
💲 Stopping Threads

😈 Results:
[SBG8300-783D] : 4wHS: 1 | PMKID: 0
[RingOfSecurity-sXJM2Bdi/] : 4wHS: 1 | PMKID: 0

📦 Creating Output Tarball (oxide-2024-04-20_22-52-27.tar.gz).
Please wait...

Complete! Happy Cracking! 🤙`

** Hardware (please complete the following information):**
 - raspberry pi zero 2 w 
 - 5.15.44-Re4son-v7+ #1 SMP Debian kali-pi (2022-07-03) armv7l GNU/Linux
 - Interface: AWUS036ACS

**Comment by Ragnt** [comment]
Have you blacklisted the panda card in network manager? This looks to me like network manager messing with it. This could also be a edge-case in re4son, but I'm not too sure about that. Whatever is happening, it looks that the device is not found at some point when we go to check on it. That error in particular is coming directly from the kernel.

**Comment by jakkpotts** [comment]
Yes, I have created a system rule to have the panda adapter not managed by NetworkManager. Would you suggest to remove the rule and instead just kill the service before I launch angryoxide?On Apr 21, 2024, at 7:42 AM, rage ***@***.***> wrote:﻿
Have you blacklisted the panda card in network manager? This looks to me like network manager messing with it. This could also be a edge-case in re4son, but I'm not too sure about that. Whatever is happening, it looks that the device is not found at some point when we go to check on it. That error in particular is coming directly from the kernel.

**Comment by jakkpotts** [comment]
Yes, I have created a system rule to have the panda adapter not managed by NetworkManager. Would you suggest to remove the rule and instead just kill the service before I launch angryoxide? On Apr 21, 2024, at 7:42 AM, rage ***@***.***> wrote: Have you blacklisted the panda card in network manager? This looks to me like network manager messing with it. This could also be a edge-case in re4son, but I'm not too sure about that. Whatever is happening, it looks that the device is not found at some point when we go to check on it. That error in particular is coming directly from the kernel. — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you authored the thread. Message ID: ***@***.***>

**Comment by Ragnt** [comment]
It's certainly worth a try. I would be interested to see what dmesg is putting out around the same time as it crashes as well.
