### ISSUE TITLE
Isn't automated like Fluxion?

### ISSUE THREAD

**Issue by hyzo90** [Ragnt/AngryOxide#37]
Was looking around for better version of Fluxion and came across this. Was wondering if it works like Fluxion. everything is automated and user friendly

**Comment by Ragnt** [comment]
AO isn’t quite the same as fluxion; we aren’t running a phishing attack against the user to retrieve a PSK in plaintext. This is purely a WPA attack tool, designed to exclusively to obtain a valid EAPoL collection using a variety of methods.
