### ISSUE TITLE
Plugin Framework

### ISSUE THREAD

**Issue by Ragnt** [Ragnt/AngryOxide#5]

**Comment by 00JCIV00** [comment]
![RoughIdea](https://github.com/Ragnt/AngryOxide/assets/68087632/22a04800-1ec6-4070-97f1-ec52488b0f5b)

**Comment by TheRedhawk404** [comment]
getting error like " `error: Permission denied (os error 13) at path "/home/redhawk/Desktop/wifi Pentesting/AngryOxide/targetNdgCVF`"
make: *** [Makefile:16: build] Error 101" how to fix this

**Comment by Ragnt** [comment]
> getting error like " `error: Permission denied (os error 13) at path "/home/redhawk/Desktop/wifi Pentesting/AngryOxide/targetNdgCVF" make: *** [Makefile:16: build] Error 101`" how I can fix it

This is the wrong place for this.

Please create your own issue with relevant details such as operating system and version.

**Comment by 00JCIV00** [comment]
# AO Plugin Design Draft

## Implementation
- Dynamic Loading of Shared Objects
- Possibly incorporate ipc or WebSockets down the road?

## Trigger Points
### Initialization
- Handle during OxideRuntime
- Pass init data:
    - State
    - Interface
    - Channel(s?)
    - Targets

### GPS
- Handle as alt source? (Pull)
- Allow exporting current GPS data? (Push)

### Frame Detection
- Handle during post-processing
- Pass target info

### Clean Up
- Handle after Thread Stopping?

## Considerations
- Get sync working, then async
- Create a `--no-plugins` mode
- Where should plugins be read from?
